### PR TITLE
quoted description  string

### PR DESCRIPTION
**Pull request by Alessandro-Barbieri**
fixes https://github.com/allenh1/superflore/issues/3

### CODE REVIEW

**Comment by allenh1** [comment]
@Alessandro-Barbieri seems the CI doesn't like this.

**Comment by allenh1** [comment]
Did you mean to pull in `quotes`?

```
shlex.quotes
   Characters that will be considered string quotes. The token accumulates until the same quote is 
   encountered again (thus, different quote types protect each other as in the shell.) By default, includes 
   ASCII single and double quotes.
```

If so, I don't think that's the fix here. I'd strongly prefer just a simple `.replace`.

**Comment by Alessandro-Barbieri** [comment]
> Did you mean to pull in `quotes`?

No, python3's `shlex.quote` that was python2.7's  `pipe.quote`

```
shlex.quote(s)
 
Return a shell-escaped version of the string s. The returned value is a string that can safely be used as one token in a shell command line, for cases where you cannot use a list.
```
> I'd strongly prefer just a simple .replace.

Potentially this will let open some other vulnerabilities

https://xkcd.com/327/

^^

**Comment by allenh1** [comment]
Ok, that's fine then.

Should these modules be there by default, or do they need to be added to the `setup.py` file?

**Comment by Alessandro-Barbieri** [comment]
These modules are in the standard python library

**Pull request merged**
