### PR TITLE
use arch independent path

### PR DESCRIPTION
**Pull request by Alessandro-Barbieri**

### CODE REVIEW

**Comment by Alessandro-Barbieri** [comment]
lib64 is obviously a 64 bits architecture only folder

**Comment by allenh1** [comment]
@Alessandro-Barbieri That's a fair point.

**Comment by allenh1** [comment]
@Alessandro-Barbieri This is good to merge after that conflict is resolved.

**Comment by allenh1** [comment]
Also pulled in with #28

**Pull request closed without merging**
